### ISSUE TITLE
Return pairs.tsv from CheckStateMachine

### ISSUE THREAD

**Issue by alexiswl** [umccr/holmes#19]
CheckStateMachine currently just returns the html in string format.  

Would be programmatically easier to parse out the pairs.tsv output in string format and run queries on the output dataframe.  

I tried rendering the HTML in databricks, it shows it but never stops adding onto the iframe size which makes a very strange output.

**Comment by andrewpatto** [comment]
I have the actual somalier tsv outputs (pairs+) - so I can easily add a function that does a return of them..

**Comment by andrewpatto** [comment]
There is a new 'relate' command that returns this
